### ISSUE TITLE
Luca Pinto - Week 2 Ticket: Work on user login

### ISSUE THREAD

**Issue by NiharMarar** [NiharMarar/p4lavalamps#10]
Link to Code: https://github.com/NiharMarar/p4lavalamps/blob/c18616daac0a9c0754f707ce0fbdf3cb956a31fe/templates/login.html#L1 
Self Grade:
3/3 All requirements met, ticket was worked on and links produced.
Reviewed by: Colin Tran

**Comment by lucap2527** [comment]
Link to Code: https://github.com/NiharMarar/p4lavalamps/blob/c18616daac0a9c0754f707ce0fbdf3cb956a31fe/templates/login.html#L1 
Self Grade:
3/3 All requirements met, ticket was worked on and links produced.
Reviewed by: Colin Tran

**Comment by jm1021** [comment]
Thanks for issue.  Requirement ask for link to runtime.  Also, I not actually sure what you did as html page has for lop and is processing some sort of data.  Nihar could make a comment and be more clear on his verification. 2/3, +2 because of team effort.

**Comment by gracele246** [comment]
Very nice code. It is organized and the links to code are there.

**Comment by noahahooja** [comment]
Very organized ticket, well done with links to tangibles and evidence of completion.

**Comment by LordRoop** [comment]
Very well organized. Tangible code links are present. Very self explanatory 10/10
