### ISSUE TITLE
- [ ] Francis Lim - Week 2 Ticket: Work on fixing bubble sort code and display information on website

### ISSUE THREAD

**Issue by lim04francis** [NiharMarar/p4lavalamps#4]
Week 2 Ticket Description: Worked on fixing bubble sort code and worked on attempt to display information on separate html page on website, collaborated with Bryce

Self grade and Review: 
Grading 3/3: Bubble sort code completed and evaluated for use, progress made towards displaying information on website on bubble sort html page
Reviewed by Bryce and Nihar

Tangibles For Completed Work: 
-Link to bubblesort python code: https://github.com/NiharMarar/p4lavalamps/blob/5a2468873ef9e65ccbc1dccaa2333409f76000fc/bubblesort/bfbubble/bfbubble.py#L1-L35
-Link to display information on html: https://github.com/NiharMarar/p4lavalamps/blob/5a2468873ef9e65ccbc1dccaa2333409f76000fc/bubblesort/bfbubble/templates/bfbubble.html#L1-L166
-Link to blueprint python code: https://github.com/NiharMarar/p4lavalamps/blob/5a2468873ef9e65ccbc1dccaa2333409f76000fc/bubblesort/bfbubble/app.py#L1-L17
Runtime link in progress by scrum member

**Comment by lim04francis** [comment]
Tangibles For Completed Work: 
-Link to bubblesort python code: https://github.com/NiharMarar/p4lavalamps/blob/5a2468873ef9e65ccbc1dccaa2333409f76000fc/bubblesort/bfbubble/bfbubble.py#L1-L35
-Link to display information on html: https://github.com/NiharMarar/p4lavalamps/blob/5a2468873ef9e65ccbc1dccaa2333409f76000fc/bubblesort/bfbubble/templates/bfbubble.html#L1-L166
-Link to blueprint python code: https://github.com/NiharMarar/p4lavalamps/blob/5a2468873ef9e65ccbc1dccaa2333409f76000fc/bubblesort/bfbubble/app.py#L1-L17

**Comment by jm1021** [comment]
Very cool ticket.  Nice embed of source.  How did you do it?  You will need to show me your method.  Missing runtime link and reviewer which will cost point. 2/3, +2 for team effort.
