### ISSUE TITLE
Bryce Modugno - Week 2 Ticket: Fixing bubble sort code and displaying information on website

### ISSUE THREAD

**Issue by MrMadman33** [NiharMarar/p4lavalamps#5]
3/3 points self grade

Francis and I scrapped the project that we had originally worked on with the Bubble Sorting and resorted to a different template. Attached link is the github code. 

https://github.com/NiharMarar/p4lavalamps/tree/main/bubblesort/bfbubble

**Comment by MrMadman33** [comment]
Peer checked by: Nihar

**Comment by jm1021** [comment]
Github link looks good.  There looks to be some real python code there.  I am looking for a runtime link.  But glad to see this effort 2/3 on task +2 because of team effort.
