### ISSUE TITLE
Nihar Marar - Week 2 Ticket: Add the news page and potentially add a news api or get started on that

### ISSUE THREAD

**Issue by NiharMarar** [NiharMarar/p4lavalamps#8]
Adding a news page as well as a news api for updated information as we have the data from the table but we also want the news like vaccinations, mask mandates, etc

https://github.com/NiharMarar/p4lavalamps/blob/6f1edcb2132cf0d56a263a9cccf354ed7b79b64a/main.py#L92-L94

https://github.com/NiharMarar/p4lavalamps/blob/6f1edcb2132cf0d56a263a9cccf354ed7b79b64a/templates/navigation.html#L1-L252

https://github.com/NiharMarar/p4lavalamps/blob/6f1edcb2132cf0d56a263a9cccf354ed7b79b64a/templates/news.html#L1-L114

**Comment by NiharMarar** [comment]
Here are the links to my code as shown above. I added the news.html, added the Jinja so that we didn't have to reuse the navigation bar. I added the navigation bar. I also made sure the website had no bugs.

**Comment by NiharMarar** [comment]
Was reviewed by Francis and Luca

**Comment by NiharMarar** [comment]
3/3

**Comment by jm1021** [comment]
Links are very nice.  I like the evidence.  No runtime makes it tough for me to visualize progress.  2/3 +2 for team effort

**Comment by gracele246** [comment]
Very nice tickets with the links working. Very organized as well.
