### ISSUE TITLE
Colin Tran - Week 2 Ticket: Get the deployment done and the runtime link working

### ISSUE THREAD

**Issue by NiharMarar** [NiharMarar/p4lavalamps#9]
Self grade 3/3:
Worked on AWS deployment since pi didn't work. No tangibles as it is deployment.
Reviewed by Nihar

**Comment by colinktran** [comment]
Self grade 3/3:
Worked on AWS deployment since pi didn't work. No tangibles as it is deployment.
Reviewed by Nihar

**Comment by colinktran** [comment]
> Self grade 3/3:
> Worked on AWS deployment since pi didn't work. No tangibles as it is deployment.
> Reviewed by Nihar

**Comment by colinktran** [comment]
Self grade 3/3:
Worked on AWS deployment since pi didn't work. No tangibles as it is deployment.
Reviewed by Nihar

**Comment by jm1021** [comment]
Colin, we need to get this done.  It is holding team back.  1/3 +2 for team effort
